# -*- coding: utf-8 -*-
"""Controle_Financeiro_Patota.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaDpgaFzw2jYa5vPDH_2Aq-6BnwvIk7w
"""

# --- PASSO 0: INSTALAÇÃO DA FERRAMENTA (Se der erro, descomente a linha abaixo) ---
!pip install xlsxwriter

import pandas as pd
from datetime import date

print("Iniciando a geração do Banco de Dados da Patota...")

# 1. ABA: BASE DE JOGADORES (Dimensão)
jogadores_data = [
    {"Nome": "Alexandre Romero", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Gabriel Ferreira Mohr", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Jean Souza Patota", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Thomas Eletrica ALT", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Jucemar", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Giovane Luiz Altenburg", "Categoria": "Titular", "Status": "DM", "Pix_Padrao": 45.00, "Obs": "Paga Fev e para"},
    {"Nome": "Vanderli", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Marcelo Segala Altenburg", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Mateus Altenburg", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Hiago Gomes", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00},
    {"Nome": "Cauã", "Categoria": "Titular", "Status": "Ativo", "Pix_Padrao": 45.00, "Obs": "Promovido em Fev"},
    {"Nome": "Maurício Altenburg", "Categoria": "Goleiro", "Status": "Ativo", "Pix_Padrao": 20.00},
    {"Nome": "Thiago", "Categoria": "Goleiro", "Status": "Ativo", "Pix_Padrao": 20.00},
    {"Nome": "Magrão", "Categoria": "Visitante", "Status": "Visitante", "Pix_Padrao": 10.00},
    {"Nome": "Patrick", "Categoria": "Visitante", "Status": "Visitante", "Pix_Padrao": 10.00},
    {"Nome": "André", "Categoria": "Visitante", "Status": "Visitante", "Pix_Padrao": 10.00},
    {"Nome": "Cleverson Fellipe", "Categoria": "Visitante", "Status": "Visitante", "Pix_Padrao": 10.00},
]
df_jogadores = pd.DataFrame(jogadores_data)

# 2. ABA: FLUXO DE CAIXA (Fatos - Jan e Fev consolidados)
fluxo_data = [
    # --- JANEIRO 2026 ---
    {"Data": "2026-01-01", "Mes_Ref": "Janeiro", "Nome": "Sistema", "Tipo": "Entrada", "Categoria": "Saldo Inicial", "Valor": 190.06, "Status": "Pago"},
    {"Data": "2026-01-13", "Mes_Ref": "Janeiro", "Nome": "Alexandre Romero", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-13", "Mes_Ref": "Janeiro", "Nome": "Maurício Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 20.00, "Status": "Pago"},
    {"Data": "2026-01-12", "Mes_Ref": "Janeiro", "Nome": "Gabriel Ferreira Mohr", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-12", "Mes_Ref": "Janeiro", "Nome": "Jean Souza Patota", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-12", "Mes_Ref": "Janeiro", "Nome": "Thomas Eletrica ALT", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-08", "Mes_Ref": "Janeiro", "Nome": "Jucemar", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-08", "Mes_Ref": "Janeiro", "Nome": "Giovane Luiz Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-08", "Mes_Ref": "Janeiro", "Nome": "Vanderli", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-07", "Mes_Ref": "Janeiro", "Nome": "Marcelo Segala Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-07", "Mes_Ref": "Janeiro", "Nome": "Mateus Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-01-12", "Mes_Ref": "Janeiro", "Nome": "Hiago Gomes", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 55.00, "Status": "Pago"},
    {"Data": "2026-01-12", "Mes_Ref": "Janeiro", "Nome": "Bruno Cunha (Quadra)", "Tipo": "Entrada", "Categoria": "Estorno", "Valor": 30.00, "Status": "Pago"},
    {"Data": "2026-01-12", "Mes_Ref": "Janeiro", "Nome": "Bruno Cunha (Quadra)", "Tipo": "Saída", "Categoria": "Aluguel", "Valor": -430.00, "Status": "Pago"},
    {"Data": "2026-01-31", "Mes_Ref": "Janeiro", "Nome": "Thiago", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 20.00, "Status": "Pendente"},
    {"Data": "2026-01-31", "Mes_Ref": "Janeiro", "Nome": "Magrão", "Tipo": "Entrada", "Categoria": "Visitante", "Valor": 20.00, "Status": "Pendente"},
    {"Data": "2026-01-31", "Mes_Ref": "Janeiro", "Nome": "Patrick", "Tipo": "Entrada", "Categoria": "Visitante", "Valor": 20.00, "Status": "Pendente"},
    {"Data": "2026-01-31", "Mes_Ref": "Janeiro", "Nome": "André", "Tipo": "Entrada", "Categoria": "Visitante", "Valor": 10.00, "Status": "Pendente"},
    {"Data": "2026-01-31", "Mes_Ref": "Janeiro", "Nome": "Cleverson Fellipe", "Tipo": "Entrada", "Categoria": "Visitante", "Valor": 10.00, "Status": "Pendente"},
    {"Data": "2026-01-31", "Mes_Ref": "Janeiro", "Nome": "Cauã", "Tipo": "Entrada", "Categoria": "Visitante", "Valor": 10.00, "Status": "Pendente"},
    # --- FEVEREIRO 2026 ---
    {"Data": "2026-02-09", "Mes_Ref": "Fevereiro", "Nome": "Vanderli", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-02-09", "Mes_Ref": "Fevereiro", "Nome": "Maurício Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 20.00, "Status": "Pago"},
    {"Data": "2026-02-09", "Mes_Ref": "Fevereiro", "Nome": "Jucemar", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-02-09", "Mes_Ref": "Fevereiro", "Nome": "Thomas Eletrica ALT", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-02-09", "Mes_Ref": "Fevereiro", "Nome": "Gabriel Ferreira Mohr", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-02-06", "Mes_Ref": "Fevereiro", "Nome": "Mateus Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-02-06", "Mes_Ref": "Fevereiro", "Nome": "Marcelo Segala Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pago"},
    {"Data": "2026-02-10", "Mes_Ref": "Fevereiro", "Nome": "Alexandre Romero", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pendente"},
    {"Data": "2026-02-10", "Mes_Ref": "Fevereiro", "Nome": "Jean Souza Patota", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pendente"},
    {"Data": "2026-02-10", "Mes_Ref": "Fevereiro", "Nome": "Giovane Luiz Altenburg", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pendente"},
    {"Data": "2026-02-10", "Mes_Ref": "Fevereiro", "Nome": "Hiago Gomes", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pendente"},
    {"Data": "2026-02-10", "Mes_Ref": "Fevereiro", "Nome": "Cauã", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 45.00, "Status": "Pendente"},
    {"Data": "2026-02-10", "Mes_Ref": "Fevereiro", "Nome": "Thiago", "Tipo": "Entrada", "Categoria": "Mensalidade", "Valor": 20.00, "Status": "Pendente"},
    {"Data": "2026-02-15", "Mes_Ref": "Fevereiro", "Nome": "Bruno Cunha (Quadra)", "Tipo": "Saída", "Categoria": "Aluguel", "Valor": -400.00, "Status": "Agendado"},
]
df_fluxo = pd.DataFrame(fluxo_data)

# 3. ABA: PARAMETROS
parametros_data = [
    {"Parametro": "Valor_Mensalista", "Valor": 45.00},
    {"Parametro": "Valor_Goleiro", "Valor": 20.00},
    {"Parametro": "Valor_Visitante", "Valor": 10.00},
    {"Parametro": "Custo_Quadra", "Valor": 400.00},
    {"Parametro": "Meta_Reserva", "Valor": 800.00},
]
df_parametros = pd.DataFrame(parametros_data)

# Gerar Excel
nome_arquivo = "Controle_Financeiro_Patota.xlsx"
with pd.ExcelWriter(nome_arquivo, engine='xlsxwriter') as writer:
    df_jogadores.to_excel(writer, sheet_name='Base_Jogadores', index=False)
    df_fluxo.to_excel(writer, sheet_name='Fluxo_Caixa', index=False)
    df_parametros.to_excel(writer, sheet_name='Parametros', index=False)

    # Formatação visual
    workbook = writer.book
    money_fmt = workbook.add_format({'num_format': 'R$ #,##0.00'})
    worksheet = writer.sheets['Fluxo_Caixa']
    worksheet.set_column('F:F', 15, money_fmt)
    worksheet.set_column('A:E', 18)

print(f"✅ Sucesso! O arquivo '{nome_arquivo}' foi gerado.")

"""# Nova seção

# Nova seção
"""